name: Hotfix PR Merge Detailed File Changes

on:
  pull_request:
    types: [closed]

jobs:
  hotfix-file-details:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_BQ_SERVICE_ACCOUNT_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - name: Verify BigQuery access
        run: |
        echo "Checking BigQuery datasets..."
        bq ls --project_id="$PROJECT_ID"
      - name: Log basic PR info
        run: |
          echo "Hotfix PR #${{ github.event.pull_request.number }} merged"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Title: ${{ github.event.pull_request.title }}"

      - name: Get detailed changed files from GitHub API
        id: files
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              }
            );

            const fileDetails = files.map(f => ({
              filename: f.filename,
              status: f.status,
              additions: f.additions,
              deletions: f.deletions
            }));

            const json = JSON.stringify(fileDetails, null, 2);
            console.log(json);

            return json

      - name: Write file details JSON to disk
        run: echo '${{ steps.files.outputs.result }}' > hotfix-file-changes.json

      - name: Upload file details artifact
        uses: actions/upload-artifact@v4
        with:
          name: hotfix-file-changes
          path: hotfix-file-changes.json

