name: Hotfix PR Merge Detailed File Changes

on:
  pull_request:
    types: [closed]

jobs:
  hotfix-file-details:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest

    env:
      DATASET: sandbox_dataset
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_BQ_SERVICE_ACCOUNT_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - name: Generate PR JSON data
        run: |
          # Convert timestamps to epoch seconds
          created=$(date -d "${{ github.event.pull_request.created_at }}" +%s)
          merged=$(date -d "${{ github.event.pull_request.merged_at }}" +%s)

          # Calculate time to merge in seconds or null
          if [[ -z "$created" || -z "$merged" ]]; then
            time_to_merge=null
          else
            time_to_merge=$((merged - created))
          fi

          # Convert merged_at to microseconds since epoch (BigQuery TIMESTAMP logicalType expects microseconds)
          merge_timestamp_us=$((merged * 1000000))

          jq -n \
            --arg pr_number "${{ github.event.pull_request.number }}" \
            --arg repo "${{ github.repository }}" \
            --arg pr_id "${{ github.event.pull_request.node_id }}" \
            --arg branch_name "${{ github.event.pull_request.head.ref }}" \
            --arg incident_id "" \
            --arg title "${{ github.event.pull_request.title }}" \
            --argjson merge_timestamp "$merge_timestamp_us" \
            --argjson total_files_changed "${{ github.event.pull_request.changed_files }}" \
            --argjson total_additions "${{ github.event.pull_request.additions }}" \
            --argjson total_deletions "${{ github.event.pull_request.deletions }}" \
            --argjson time_to_merge_secs "$time_to_merge" \
            '{
              pr_number: ($pr_number | tonumber),
              repo: $repo,
              pr_id: $pr_id,
              branch_name: $branch_name,
              incident_id: ($incident_id | if . == "" then null else . end),
              title: ($title | if . == "" then null else . end),
              merge_timestamp: (if $merge_timestamp == 0 then null else $merge_timestamp end),
              total_files_changed: ($total_files_changed | if . == 0 then null else . end),
              total_additions: ($total_additions | if . == 0 then null else . end),
              total_deletions: ($total_deletions | if . == 0 then null else . end),
              time_to_merge_secs: (if $time_to_merge_secs == null then null else $time_to_merge_secs end)
            }' > pr_data.json

          jq -c .pr_data.json > pr_data_compact.json
          cat pr_data_compact.json

      - name: Extract PR file metadata and write NDJSON
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"

          gh pr view "$PR_NUMBER" --repo "$REPO" --json files --jq '
            .files[] |
            {
              pr_id: "'"$PR_NUMBER"'",
              filename: .path,
              additions: .additions,
              deletions: .deletions,
              status: .status,
              file_extension: (if (.path | test("\\.")) then "." + (.path | split(".")[-1]) else null end),
              top_level_dir: (.path | split("/")[0])
            }
          ' | jq -c '.' > files.ndjson
          echo "Changed files JSON generated:"
          cat files.ndjson

      - name: Load hotfix_pr JSON into BigQuery
        run: |
          cat pr_data_compact.json
          bq load \
            --project_id=$PROJECT_ID \
            --source_format=NEWLINE_DELIMITED_JSON \
            --replace \
            $DATASET.hotfix_pr \
            ./pr_data_compact.json \
            ./schemas/hotfix_pr.json
