name: On PR Merged to Main

on:
  pull_request:
    types: [closed]

jobs:
  analyze-merged-pr:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Print PR metadata
        run: |
          echo "PR #${{ github.event.pull_request.number }} was merged to 'main'"
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"

      - name: Get changed files using GitHub API
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              }
            );

            console.log(`Changed files in PR #${pr.number}:`);
            for (const file of files) {
              console.log(`- ${file.filename} (${file.status})`);
            }

