name: Hotfix PR Metadata Workflow

on:
  pull_request:
    types: [closed]

jobs:
  hotfix-metadata:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
