name: Hotfix PR Merge Detailed File Changes

on:
  pull_request:
    types: [closed]

jobs:
  hotfix-file-details:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest

    steps:
      - name: Log basic PR info
        run: |
          echo "Hotfix PR #${{ github.event.pull_request.number }} merged"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Title: ${{ github.event.pull_request.title }}"

      - name: Get detailed changed files from GitHub API
        id: files
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              }
            );

            // Build an array with detailed info for each file
            const fileDetails = files.map(f => ({
              filename: f.filename,
              status: f.status,
              additions: f.additions,
              deletions: f.deletions
            }));

            console.log(JSON.stringify(fileDetails, null, 2));

            return JSON.stringify(fileDetails);
      
      - name: Save file details JSON to artifact
        uses: actions/upload-artifact@v3
        with:
          name: hotfix-file-changes
          path: ${{ steps.files.outputs.result }}

